id: product
displayName: Product
path: /single
custom:
  allowedContentTypes:
    - product
method: GET
archetype: singleEntry
variables:
  entryId:
    type: text
    default: ''
dataSourceId: uniland
allowedOnComponents: []
