id: productList
displayName: Product List
path: /query
custom:
  allowedContentTypes:
    - product
method: GET
archetype: queryEntries
variables:
  limit:
    type: text
    default: '10'
  offset:
    type: text
    default: '0'
  orderBy:
    type: text
    default: ''
  contentTypes:
    type: text
    default: ''
dataSourceId: uniland
allowedOnComponents: []
