id: productList
displayName: Product List
ttl: 30
path: /query
custom:
  maxDepth: 2
  proposedName: Query Product
  allowedContentTypes:
    - product
method: GET
purgeKey: 841c2501-f694-4416-b27d-2cffde4afd7a
archetype: queryEntries
variables:
  limit:
    type: text
    default: '20'
  offset:
    type: text
    default: '0'
  filters:
    type: text
    default: '{}'
  orderBy:
    type: text
    default: ''
  contentTypes:
    type: text
    default: ''
dataSourceId: uniformContent
allowedOnComponents: []
