id: productCollectionBySlug
displayName: Product collection by slug
ttl: 30
path: /single-by-slug
custom:
  maxDepth: 2
  proposedName: Product collection
  allowedContentTypes:
    - productCollection
method: GET
purgeKey: 06382b18-1c83-49c0-a083-e85e0ab13505
archetype: singleEntryBySlug
variables:
  slug:
    type: text
    default: ''
dataSourceId: uniformContent
allowedOnComponents: []
