id: recipe
displayName: Recipe
ttl: 30
path: /single
custom:
  maxDepth: 3
  proposedName: Recipe
  allowedContentTypes:
    - recipe
method: GET
purgeKey: 09a51ce6-c656-40ed-93d7-af3cbf26066e
archetype: singleEntry
variables:
  entryId:
    type: text
    default: ''
dataSourceId: uniformContent
allowedOnComponents: []
