id: productByHandle
displayName: Product by handle
ttl: 30
path: ''
custom:
  proposedName: ''
method: GET
purgeKey: 830c1079-de47-4730-b892-042df8760a03
archetype: default
variables:
  handle:
    type: text
    default: men-crewneck
    helpText: URL slug of the product
parameters:
  - key: query
    value: >-
      { product(handle: "${handle}") { id title description availableForSale
      productType handle collections(first: 3) { edges { node { id title
      description handle image { url width height altText id } } } }
      featuredImage { id url } variants(first: 3) { edges { cursor node { id
      title image { url } price { amount currencyCode } } } } }}
longTermCache:
  enabled: false
  ttlInHours: 24
dataSourceId: mockShop
allowedOnComponents: []
