id: productCollection
name: Product collection
created: '2023-12-05T10:04:09.268635+00:00'
updated: '2025-05-13T09:21:13.795949+00:00'
slugSettings:
  required: 'no'
useTeamPermissions: true
fields:
  - id: name
    name: Name
    type: text
    typeConfig: null
    localizable: true
  - id: reference
    name: Reference
    type: text
    typeConfig: null
    localizable: true
  - id: description
    name: Description
    type: richText
    typeConfig:
      elements:
        builtIn:
          - h1
          - h2
          - h3
          - h4
          - h5
          - h6
          - unorderedList
          - orderedList
          - link
          - quote
          - code
          - variable
      required: false
      formatting:
        builtIn:
          - bold
          - italic
          - underline
          - strikethrough
          - code
          - superscript
          - subscript
    localizable: true
  - id: image
    name: Image
    type: asset
    typeConfig:
      max: 1
    localizable: true
    notLocalizedByDefault: true
  - id: products
    name: Products
    type: contentReference
    helpText: ''
    typeConfig:
      isMulti: true
      allowedContentTypes:
        - product
    localizable: false
  - id: externalProducts
    name: External Products
    type: $block
    helpText: ''
    typeConfig:
      allowedTypes:
        - $loop
        - productVariant
entryName: name
thumbnailField: image
description: ''
icon: shopping-cart
type: contentType
permissions: []
previewConfigurations: []
