id: productOptions
name: Product Options
created: '2024-08-02T17:20:39.252664+00:00'
updated: '2024-08-02T17:21:37.493581+00:00'
slugSettings:
  required: 'no'
useTeamPermissions: true
fields:
  - id: name
    name: Name
    type: text
    helpText: ''
    typeConfig: null
    localizable: false
  - id: options
    name: Options
    type: $block
    helpText: ''
    typeConfig:
      allowedTypes:
        - taxonomyBlock
        - $loop
entryName: name
description: ''
icon: shopping-cart
type: block
permissions: []
previewConfigurations: []
