id: product
name: Product
created: '2023-06-30T14:25:25.628227+00:00'
updated: '2024-07-31T09:09:31.426031+00:00'
slugSettings:
  unique: local
  required: 'no'
  regularExpression: ''
  regularExpressionMessage: ''
useTeamPermissions: true
fields:
  - id: name
    name: Name
    type: text
    helpText: ''
    typeConfig: null
    localizable: true
  - id: teaserText
    name: Teaser Text
    type: text
    helpText: ''
    typeConfig:
      multiline: true
      linesCount: 2
    localizable: true
  - id: description
    name: Description
    type: richText
    helpText: ''
    typeConfig:
      elements:
        builtIn:
          - h1
          - h2
          - h3
          - h4
          - h5
          - h6
          - unorderedList
          - orderedList
          - link
          - quote
          - code
          - variable
      required: false
      formatting:
        builtIn:
          - bold
          - italic
          - underline
          - strikethrough
          - code
          - superscript
          - subscript
    localizable: true
  - id: group_media
    name: Media
    type: group
    typeConfig:
      collapsed: false
      childrenParams:
        - featuredImage
        - images
        - media
        - media2
  - id: featuredImage
    name: Featured Image
    type: asset
    helpText: ''
    typeConfig:
      max: 1
    localizable: true
  - id: images
    name: Images
    type: asset
    helpText: ''
    typeConfig:
      min: 0
    localizable: true
  - id: media
    name: Media
    type: $block
    helpText: Used for connecting to external media
    typeConfig:
      allowedTypes:
        - $loop
        - imageBlock
  - id: media2
    name: Media2
    type: $block
    helpText: ''
    typeConfig:
      allowedTypes: all
  - id: group_productSettings
    name: Product settings
    type: group
    typeConfig:
      collapsed: false
      childrenParams:
        - reference
        - collections
        - variants
  - id: reference
    name: Reference
    type: text
    helpText: ''
    typeConfig: null
  - id: collections
    name: Collections
    type: $block
    helpText: ''
    typeConfig:
      allowedTypes:
        - taxonomyBlock
        - $loop
  - id: variants
    name: Variants
    type: $block
    helpText: ''
    typeConfig:
      allowedTypes:
        - productVariant
        - $loop
entryName: name
thumbnailField: featuredImage
description: ''
icon: shopping-cart
type: contentType
permissions: []
