id: product
name: Product
created: '2023-06-30T14:25:25.628227+00:00'
updated: '2024-01-24T13:34:03.66426+00:00'
slugSettings:
  required: 'no'
useTeamPermissions: true
fields:
  - id: name
    name: Name
    type: text
    helpText: ''
    typeConfig: null
    localizable: true
  - id: reference
    name: Reference
    type: text
    helpText: ''
    typeConfig: null
  - id: description
    name: Description
    type: richText
    helpText: ''
    typeConfig:
      elements:
        builtIn:
          - h1
          - h2
          - h3
          - h4
          - h5
          - h6
          - unorderedList
          - orderedList
          - link
          - quote
          - code
          - variable
      required: false
      formatting:
        builtIn:
          - bold
          - italic
          - underline
          - strikethrough
          - code
          - superscript
          - subscript
    localizable: true
  - id: featuredImage
    name: Featured Image
    type: asset
    helpText: ''
    typeConfig:
      max: 1
    localizable: true
  - id: images
    name: Images
    type: asset
    helpText: ''
    typeConfig:
      min: 0
    localizable: true
  - id: variants
    name: Variants
    type: $block
    helpText: ''
    typeConfig:
      allowedTypes:
        - productVariant
        - $loop
  - id: collections
    name: Collections
    type: $block
    helpText: ''
    typeConfig:
      allowedTypes:
        - taxonomyBlock
        - $loop
entryName: name
thumbnailField: featuredImage
description: ''
icon: shopping-cart
type: contentType
permissions: []
